version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - '/mnt/data/.phabricator-data:/bitnami'
  phabricator:
    image: 'registry.cn-hongkong.aliyuncs.com/cmzz_prod/phabricator:latest'
    ports:
      - '8070:80'
      - '8443:443'
    volumes:
      - '/mnt/data/.phabricator-data:/bitnami'
    depends_on:
      - mariadb
